#!/bin/bash
pushd step01
echo
echo "Making step01, hashDef: executable and preprocessed"
make hashDef
g++ -E ./hashDef.cc -o hashDef.prep
popd 2>&1 >/dev/null

echo
echo "Making step02, templates: executable and preprocessed"
pushd step02
make templates
g++ -E ./templates.cc -o templates.prep
popd 2>&1 >/dev/null
echo

